In [61]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np 
from sklearn.datasets import load_digits
#we want to classify the data in classes from 1-9 using this methods and then evaluate the performance of each method

digits =load_digits()

In [80]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(digits.data,digits.target,test_size=0.3)

In [63]:
len(x_test)

540

In [64]:
#first classifier "LogisticRegression"
lr=LogisticRegression()
lr.fit(x_train,y_train)
lr.score(x_test,y_test)

C:\Users\vioritiva\AppData\Roaming\Python\Python311\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9685185185185186

In [65]:
#svm 
svm=SVC()
svm.fit(x_train,y_train)
svm.score(x_test,y_test)

0.9925925925925926

In [66]:
#Random forest
rf=RandomForestClassifier(n_estimators=40)
rf.fit(x_train,y_train)
rf.score(x_test,y_test)

0.9722222222222222

In [67]:
from sklearn.model_selection import KFold
kf=KFold(n_splits=3)
kf


KFold(n_splits=3, random_state=None, shuffle=False)

In [68]:
for train_index,test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [69]:
def get_score(model,x_train,x_test,y_train,y_test):
    model.fit(x_train,y_train)
    return model.score(x_test,y_test)

In [70]:
get_score(LogisticRegression(),x_train,x_test,y_train,y_test)

C:\Users\vioritiva\AppData\Roaming\Python\Python311\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9685185185185186

In [71]:
from  sklearn.model_selection import StratifiedKFold
folds=StratifiedKFold(n_splits=3)


In [72]:
scores_logistic = []
scores_svm = []
scores_rf = []

for train_index, test_index in folds.split(digits.data,digits.target):
    x_train, x_test, y_train, y_test = digits.data[train_index], digits.data[test_index], \
                                       digits.target[train_index], digits.target[test_index]
    scores_logistic.append(get_score(LogisticRegression(solver='liblinear',multi_class='ovr'), x_train, x_test, y_train, y_test))  
    scores_svm.append(get_score(SVC(gamma='auto'), x_train, x_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40), x_train, x_test, y_train, y_test))

In [73]:
scores_logistic

[0.8948247078464107, 0.9532554257095158, 0.9098497495826378]

In [74]:
scores_svm

[0.3806343906510851, 0.41068447412353926, 0.5125208681135225]

In [75]:
scores_rf

[0.9298831385642737, 0.9549248747913188, 0.9282136894824707]

In [76]:
from sklearn.model_selection import cross_val_score

In [77]:
#this method do the same thing like for loop above
cross_val_score(LogisticRegression(),digits.data,digits.target)

C:\Users\vioritiva\AppData\Roaming\Python\Python311\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\vioritiva\AppData\Roaming\Python\Python311\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/l

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [82]:
cross_val_score(SVC(),digits.data,digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

Exercise

In [83]:
from sklearn import tree

In [84]:
from sklearn.datasets import load_iris
iris=load_iris()

In [85]:
dir(iris)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

SVM

In [101]:
scores_svm=cross_val_score(SVC(),iris.data,iris.target)
scores_svm

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [102]:
np.average(scores_svm)

0.9666666666666666

Logistic regression

In [126]:
scores_l=cross_val_score(LogisticRegression(),iris.data,iris.target)
scores_l

C:\Users\vioritiva\AppData\Roaming\Python\Python311\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [100]:
np.average(scores_l)

0.9733333333333334

decision tree

In [105]:
scoreD=cross_val_score(tree.DecisionTreeClassifier(),iris.data,iris.target)
scoreD

array([0.96666667, 0.96666667, 0.9       , 0.96666667, 1.        ])

In [106]:
np.average(scoreD)

0.9600000000000002

Random forest

In [107]:
scoreRD=cross_val_score(RandomForestClassifier(),iris.data,iris.target)
scoreRD

array([0.96666667, 0.96666667, 0.93333333, 0.93333333, 1.        ])

In [108]:
np.average(scoreRD)

0.96

In [132]:
import pandas as pd
df=pd.DataFrame(iris.data,columns=iris.feature_names)
df["type"]=iris.feature_names

ValueError: Length of values (4) does not match length of index (150)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [131]:
df.describe

<bound method NDFrame.describe of      sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]>