In [87]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [88]:
df=pd.read_csv("homeprices2.csv")
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [89]:
#soo 3adna kima rakom tshofo valeur ta3 bedrooms raha maf9oda soo li9 n3amroha soo how il faut nahssbp median ta3 les valeurs ta3 bedrooms ou ndirohom tma
median=df.bedrooms.median()

In [90]:
df.bedrooms=df.bedrooms.fillna(median) #hadi function tab3a l pandas fiha ano t3alrlna faraghat bhadik l valeur li mdinahalha
df  # hadi etap li kona fiha hia data preprocessing n3amro lfarghat ou n7o mo3tayat da5ila

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [91]:
new_df = df.drop('price',axis='columns')
new_df

area  bedrooms  age
0  2600       3.0   20
1  3000       4.0   15
2  3200       4.0   18
3  3600       3.0   30
4  4000       5.0    8
5  4100       6.0    8

In [92]:
reg = linear_model.LinearRegression()
reg.fit(new_df,df.price) #train model  appliquer linear regrission

LinearRegression()

In [93]:
reg.coef_  #area bedrooms age  coeff

array([  112.06244194, 23388.88007794, -3231.71790863])

In [94]:
reg.intercept_ #b value

221323.00186540437

In [95]:
reg.predict([[3000,3,40]])

C:\Users\vioritiva\AppData\Roaming\Python\Python311\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([498408.25158031])

In [96]:
112.06244194*3000 +23388.88007794*3-3231.71790863*40+221323.00186540437

498408.2515740244

In [97]:
reg.predict([[2500,4,5]])

C:\Users\vioritiva\AppData\Roaming\Python\Python311\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([578876.03748933])

In [98]:
hr= pd.read_csv("hiring.csv")
hr

experience  test_score  interview_score  salary
0        NaN         8.0                9   50000
1        NaN         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         NaN                7   72000
7     eleven         7.0                8   80000

In [99]:
hr.experience = hr.experience.fillna("zero")
hr

experience  test_score  interview_score  salary
0       zero         8.0                9   50000
1       zero         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         NaN                7   72000
7     eleven         7.0                8   80000

In [100]:
from word2number import w2n

In [105]:
hr.experience=hr.experience.apply(w2n.word_to_num)
hr

experience  test_score  interview_score  salary
0           0         8.0                9   50000
1           0         8.0                6   45000
2           5         6.0                7   60000
3           2        10.0               10   65000
4           7         9.0                6   70000
5           3         7.0               10   62000
6          10         NaN                7   72000
7          11         7.0                8   80000

In [106]:
median=hr.test_score.median()
median

8.0

In [115]:
hr.test_score=hr.test_score.fillna(median)
hr

experience  test_score  interview_score  salary
0           0         8.0                9   50000
1           0         8.0                6   45000
2           5         6.0                7   60000
3           2        10.0               10   65000
4           7         9.0                6   70000
5           3         7.0               10   62000
6          10         8.0                7   72000
7          11         7.0                8   80000

In [116]:
new_hr = hr.drop('salary',axis='columns')
new_hr

experience  test_score  interview_score
0           0         8.0                9
1           0         8.0                6
2           5         6.0                7
3           2        10.0               10
4           7         9.0                6
5           3         7.0               10
6          10         8.0                7
7          11         7.0                8

In [117]:
reg.fit(new_hr,hr.salary)

LinearRegression()

In [118]:
reg.coef_

array([2812.95487627, 1845.70596798, 2205.24017467])

In [119]:
reg.intercept_

17737.26346433768

In [120]:
reg.predict([[2,9,6]])

C:\Users\vioritiva\AppData\Roaming\Python\Python311\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([53205.96797671])

In [121]:
reg.predict([[12,10,10]])

C:\Users\vioritiva\AppData\Roaming\Python\Python311\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([92002.18340611])